### ISSUE TITLE
panic at Option::unwrap() when draw violin

### ISSUE THREAD

**Issue by Hijiao** [bheisler/criterion.rs#239]
I am stuck in the following error which happened at [here](https://github.com/japaric/criterion.rs/blob/87c2d3ddee18c40b9afb656e25f19f3444a40474/src/plot/summary.rs#L156)
Could anybody tell me why there is a none `xs`? And how can I avoid it? 
```
Found 1 outliers among 10 measurements (10.00%)
  1 (10.00%) high severe
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:345:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::panicking::panic
             at libcore/panicking.rs:52
   9: criterion::html::Html::generate_summary
             at /checkout/src/libcore/macros.rs:20
             at /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/criterion-0.2.4/src/plot/summary.rs:157
             at /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/criterion-0.2.4/src/html/mod.rs:595
  10: <criterion::html::Html as criterion::report::Report>::summarize
             at /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/criterion-0.2.4/src/html/mod.rs:283
  11: <criterion::report::Reports as criterion::report::Report>::summarize
             at /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/criterion-0.2.4/src/report.rs:252
  12: <criterion::benchmark::ParameterizedBenchmark<T> as criterion::benchmark::BenchmarkDefinition>::run
             at /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/criterion-0.2.4/src/benchmark.rs:667
  13: engines::main
             at /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/criterion-0.2.4/src/lib.rs:1094
             at /home/pingcap/.cargo/registry/src/github.com-1ecc6299db9ec823/criterion-0.2.4/src/lib.rs:986
             at benches/engines/mod.rs:214
             at benches/engines/mod.rs:226
  14: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  15: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  16: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:106
  17: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  18: main
  19: __libc_start_main
  20: <unknown>
```

I import it as 
```
criterion = { version = "0.2", features=['real_blackbox'] }
```
my rustc version is 
```
rustc 1.29.0-nightly (12ed235ad 2018-07-18)
```
Thanks!

**Comment by Hijiao** [comment]
It's weird that when I pass a vector of struct which has `&str` filed to the `bench_function_over_inputs()` as inputs, it panics.
here is the code:
```rust
#[derive(Debug)]
struct BenchConfig {
    name: &'static str,
    step: usize,
}

fn bench_test(bencher: &mut Bencher, config: &BenchConfig) {
    bencher.iter(|| {
        for i in 0..config.step {
            i * i;
        }
    })
}

fn main() {
    let mut criterion = Criterion::default().sample_size(10);
    let mut configs = vec![];
    configs.push(BenchConfig { name:"test_1", step: 10 });
    configs.push(BenchConfig { name:"test_2", step: 20 });
    criterion.bench_function_over_inputs("bench_test", bench_test, configs);
    criterion.final_summary();
}
```

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs, and thanks for the bug report! Thanks for your patience as well.

I haven't seen this before, but it does look like a problem. I'll take a look at it when I get a chance.

**Comment by bheisler** [comment]
I've tried your example code, but it doesn't give an error for me. I notice that your backtrace says you're using Criterion.rs 0.2.4 - this may have been fixed already. could you try setting it to use the latest git revision ([see documentation](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories)) and see if that helps?

**Comment by Hijiao** [comment]
@bheisler  you are right! When I update to 0.2.5, it doesn't give an error anymore. Thank you!
