### ISSUE TITLE
Criterion crashes with empty benchmark function

### ISSUE THREAD

**Issue by rhysd** [bheisler/criterion.rs#527]
## Environment

- Criterion: v0.3.5
- Rust: 1.56
- OS: macOS 10.15

## Repro

Initialize project

```
cargo init --lib
```

Modify `Cargo.toml`

```toml
[package]
name = "test"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

[dependencies]

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "bench"
harness = false
```

Add test benchmark at `benches/bench.rs`

```rust
use criterion::{criterion_group, criterion_main, Criterion};

fn run(c: &mut Criterion) {
    c.bench_function("test", |_| {
        // Do nothing
    });
}

criterion_group!(bench, run);
criterion_main!(bench);
```

Then run benchmark

```
cargo bench --bench bench
```

## Expected behavior

Run `bench` benchmark suite

## Actual behavior

It crashes. Here is a backtrace with `RUST_BACKTRACE=full`. The crash seemed to happen at `criterion::routine::Routine::sample`.

```
Benchmarking test: Warming up for 3.0000 sthread 'main' panicked at 'Benchmark function must call Bencher::iter or related method.', /Users/rhysd/.cargo/registry/src/github.com-1ecc6299db9ec823/criterion-0.3.5/src/bencher.rs:384:13
stack backtrace:
   0:        0x10f8d7211 - std::backtrace_rs::backtrace::libunwind::trace::h027800441f1fc8f7
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:        0x10f8d7211 - std::backtrace_rs::backtrace::trace_unsynchronized::h4d1dc087eb89c650
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10f8d7211 - std::sys_common::backtrace::_print_fmt::hf2537bbfc4d64c25
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x10f8d7211 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf1ee81583766da09
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x10f8f656b - core::fmt::write::h8dc218a6eb2426a8
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/fmt/mod.rs:1150:17
   5:        0x10f8d25da - std::io::Write::write_fmt::heef3e26d448f8c80
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/io/mod.rs:1667:15
   6:        0x10f8d8b45 - std::sys_common::backtrace::_print::h194fd71b011e1888
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x10f8d8b45 - std::sys_common::backtrace::print::h4eec350e8a08a661
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x10f8d8b45 - std::panicking::default_hook::{{closure}}::h4b7de73863cf8582
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:210:50
   9:        0x10f8d8727 - std::panicking::default_hook::h778da672ce56a579
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:227:9
  10:        0x10f8d9230 - std::panicking::rust_panic_with_hook::ha5146542f697c8af
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:624:17
  11:        0x10f6fffc5 - std::panicking::begin_panic::{{closure}}::hc9d7dd140ce3be94
  12:        0x10f6ffd87 - std::sys_common::backtrace::__rust_end_short_backtrace::h85a32eec0b549f95
  13:        0x10f8fcfae - std::panicking::begin_panic::h3c568a235d2a9972
  14:        0x10f71ec6e - criterion::routine::Routine::sample::h5e6489408f420495
  15:        0x10f719b81 - criterion::analysis::common::h8735fb547d10b2d3
  16:        0x10f7086ce - criterion::benchmark_group::BenchmarkGroup<M>::bench_function::h6558c7b6a3df7f9e
  17:        0x10f70ad28 - criterion::Criterion<M>::bench_function::haf9a161ac41e0bde
  18:        0x10f701d8d - bench::main::hab8af0900d85ddcb
  19:        0x10f6ffd96 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8020ff719a31c2ae
  20:        0x10f706e0c - std::rt::lang_start::{{closure}}::h64b39a36380ec2d9
  21:        0x10f8d975a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h5a1cefaf9bdbcf8a
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ops/function.rs:259:13
  22:        0x10f8d975a - std::panicking::try::do_call::h23fe123372bed355
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:403:40
  23:        0x10f8d975a - std::panicking::try::hbf138fd866572be5
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:367:19
  24:        0x10f8d975a - std::panic::catch_unwind::h2519b05c86de300b
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panic.rs:129:14
  25:        0x10f8d975a - std::rt::lang_start_internal::{{closure}}::hcfc5ea3a8292f213
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/rt.rs:45:48
  26:        0x10f8d975a - std::panicking::try::do_call::he693a6070bab7561
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:403:40
  27:        0x10f8d975a - std::panicking::try::hfae50c0249a87399
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:367:19
  28:        0x10f8d975a - std::panic::catch_unwind::h4897c9a509b40c85
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panic.rs:129:14
  29:        0x10f8d975a - std::rt::lang_start_internal::h9fcc861d49447111
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/rt.rs:45:20
  30:        0x10f701e19 - _main

error: bench failed
```

I don't think empty benchmark function is a normal use case. However it might accidentally happen as the result of compiler's optimization.

**Comment by lemmih** [comment]
Hi,

This is expected behaviour. It's printing out an error message and then quitting. The error message is: `Benchmark function must call Bencher::iter or related method.`

An empty benchmark function is always a fatal error and it cannot happen due to compiler optimizations.

**Comment by rhysd** [comment]
OK, thank you for clarification.
